# Code generated by chatGPT

import torch
from torch.distributions.multivariate_normal import MultivariateNormal

# Define the mean and covariance matrix for a 2-dimensional Gaussian distribution
mean = torch.tensor([0.0, 0.0])
covariance_matrix = torch.tensor([[1.0, 0.5], [0.5, 1.0]])

# Create a MultivariateNormal distribution
mvn = MultivariateNormal(mean, covariance_matrix)

# Generate samples from the distribution
samples = mvn.sample((5,))  # Generate 5 samples

print("Generated samples:")
print(samples)

# Compute the log probability of some points
points = torch.tensor([[0.0, 0.0], [1.0, 1.0], [2.0, 2.0]])
log_probs = mvn.log_prob(points)

print("Log probabilities of points:")
print(log_probs)
